# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FluentLenium
description: > # this means to ignore newlines until "baseurl:"
  FluentLenium makes the writing of acceptance tests in a fluent way possible using the power of css selectors.
  Build upon Selenium WebDriver. It helps you to write tests incredibly fast and reduce maintanance effort.
baseurl: ""
url: "http://fluentlenium.github.io/FluentLenium/"
github_username:  FluentLenium

# Build settings
markdown: kramdown
